### ISSUE TITLE
Issue with service providers?

### ISSUE THREAD

**Issue by dlucidone** [sis0k0/lazyNinjas#7] opened 2017-02-06 09:59 UTC
I'm getting 
`Uncaught (in promise): Error: No provider for Http!`

Any help. Thanks

**Comment by sis0k0** [comment] 2017-02-07 08:53
Hey @dlucidone,
When do you get that error? The app doesn't use the `NativeScriptHttpModule`. If you are trying to use `Http`, you probably should import that module.

**Comment by dlucidone** [comment] 2017-02-08 07:52
@sis0k0 , Hey thanks for the reply, I figured out this later, but now i'm getting issues with action bar .
In all pages i'm not getting action bar written in particular page at top?. Any help.Thanks

**Comment by sis0k0** [comment] 2017-02-08 07:58
@dlucidone 
If you want a different action bar on all pages, you need to define it in the component. Check out the [docs](https://docs.nativescript.org/ui/action-bar#defining-the-actionbar).

**Comment by dlucidone** [comment] 2017-02-08 08:05
@sis0k0 I have defined in all pages HTML but still they are not showing

**Comment by sis0k0** [comment] 2017-02-08 08:58
@dlucidone 
I need more information about the problem. If you share a simple reproduction, I may be able to help.

**Comment by dlucidone** [comment] 2017-02-08 09:13
@sis0k0  thanks for the quick reply - 

I have a login page where i have  used -
`this.page.actionBarHidden = true;`  to hide my action bar but as soon as reach out to my dashboard after login in -

#dashboard.html 

<ActionBar title="Lead Details" style="background-color:#ED2831; color:white">
    
    <ActionItem>
        <Label class="actionItemLabel" text="Edit" color="white" (tap)="onEdit()"></Label>
    </ActionItem>
    <ActionItem>     
    </ActionItem> 
</ActionBar>

Something like this but the action bar is showing with app name in it.

**Comment by sis0k0** [comment] 2017-02-08 11:38
I was unable to reproduce the error. Please refer to the [official documentation](http://docs.nativescript.org/ui/action-bar#action-items) and the [sdk-samples](https://docs.nativescript.org/angular/code-samples/ui/action-bar.html#action-items).
Closing this as unrelated to the repository.

**Closed as completed by sis0k0** 2017-02-08 11:38 UTC

**Comment by dlucidone** [comment] 2017-02-08 11:47
@sis0k0 I'm not able to get actionbar defined in my HTML to view. All I'm getting is app name on action bar.
